[tool.poetry]
name = "lavote-scrape"
version = "0.1.0"
description = "Scrape la county election results"
authors = ["Brian Kohan <bckohan@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
typer = "^0.12.5"
dateutils = "^0.6.12"
python-vlc = "^3.0.21203"


[tool.poetry.scripts]
scrape = "lavote_scrape.scrape:main"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
